[project]
name = "slack"
version = "0.1.0"
description = "A tool to send Slack messages."
readme = "README.md"
dependencies = [
    "mistletoe>=1.4.0",
    "requests>=2.32.3",
]

[tool.setuptools]
py-modules = ["slack", "md2blockkit"]
